---
title: "Enlightened Kent & East Sussex Telegram"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
    collapsed: false
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "docs", output_file ="index.html") }) 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lubridate)
library(mapview)
library(sp)
library(leaflet)
library(tidyverse)
library(kableExtra)
```

## Welcome {#welcome}
Welcome to the landing page for the Kent & East Sussex Enlightened Telegram community. Telegram is a chat app that many Enlightened agents around the world use to coordinate their activities, plan operations, meet for socials, and to swap cake recipes + cat memes. We presume you are here because you might be interested in things like that.

## Getting set-up on Telegram {#telegramsetup}
What to do now?  First, make sure you have [Telegram installed](https://telegram.org/) on your phone or mobile device. Then [set your Telegram username](https://telegram.org/blog/usernames-and-secret-chats-v2) to be your agent name (or something similar if it's already taken e.g. 'DrManBun-Enl').

Optionally, if you have an android phone, you might consider replacing the Telegram app with [Plus Messenger](https://play.google.com/store/apps/details?id=org.telegram.plus). It still *is* Telegram, but with a nicer interface and some additional options.

## For new players {#newplayers}
Have a look through the [new player chat rooms](#newplayerchatrooms) below, find your local region, and click on the link. This will add you to a chat room with a few local Enlightened agents who can talk you through any questions you have about the game, and in time give you permission to join the ['Verified'](#verifiedplayers) chat room for your area. By the way, as we are the green team, we're known as the frogs (and therefore as a new or unverified player, you're known as a tadpole! - although maybe just for a short time :-) )


## New player chat rooms {#newplayerchatrooms}
|  Area              |  New players                                                           |
|:------------------:|:----------------------------------------------------------------------:|
| Kent & East Sussex        | [Kent & East Sussex Tadpoles](https://t.me/joinchat/E05FQBOXIr5hrpAW1I0CqQ)   |

## For verified players {#verifiedplayers}
Verified players are Enlightened agents who are already active members of their local community, are known to players of that area or who have already been part of other Verified communities (such as the London groups > see the [London Telegram Community](https://london.theenl.uk/) which you may also wish to join). It may be that after a short time, Enlightened Agents who are already Verified would request to meet you just to see how you are getting along, and would then add you to the local Verified Telegram group. Talk to a local agent for help or any other information which you may need.

## Social events
The Enlightened in Kent & East Sussex are a pretty social bunch. We try to meet up regularly in a bar or cafe for a chat/drink, and normally build some high level portals so that we can hack high level kit together, or discuss/plan Ops. If you’re interested in this then you’ll need to ask the Agents in the Kent & East Sussex chat group for access to the Socials chat.

## Ingress Intel Total Conversion
If you haven't found it yet, there's an online Ingress map. You can browse areas of the world to see portals and links, and if you're inclined, use it to plan your fields (or which areas to destroy!). The standard version of this map can [be found here](https://ingress.com/intel), viewable through a web-browser. However some clever people have an overlay for it, called IITC. It's like the standard map, but in an app, and with more options. You can find [more details about it here](https://iitc.modos189.ru/).

## Useful bots and channels
There are a number of news channels and bots in Telegram that you might want to look at. Here's a few of our favourites.

* [Enlightened Today](https://telegram.me/IEToday) - Enlightened news, facts and fun from around the world
* [V Bot](https://telegram.me/vtgadminbot) - A bot for V related things
* [Rocks Bot](https://telegram.me/RocksBot) - A bot for Rocks related things
* [IUENG](https://t.me/IUENG) - Crossfaction Ingress Updates in English, particularly good for anomalies
* [EnlightenedUK](https://t.me/enlightenedUK) - Enlightened Ingress news - UK focused

## Community rules
Players in the Kent & East Sussex Enlightened adhere to the [Ingress community guidelines](https://support.ingress.com/hc/en-us/articles/206606858-Ingress-Community-Guidelines), in particular 'one account one player', and no 'using tools or techniques to alter or falsify your location'. It ruins the game. Please don't do it. In addition, please remember this is a game. The Resistance players are our opposition and (in-game) enemy, but they're people just like you or I. Name-calling and/or posting specific details about people 'real lives' isn't cool.

## Other platforms
* [Ingress Enlightened UK on Facebook](https://www.facebook.com/EnlightenedUK/)
* [Enlightened UK Blog](https://enlighteneduk.blog/)
